# Generated by Django 5.0.4 on 2024-04-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=32)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('zipcode', models.CharField(max_length=5, unique=True)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
